name: Rehan Practice JS Actions
description: This action greets persons
inputs:
  person:
      description: 'The person to greet'
      required: true
      default: 'Monalisa'

runs:
  using: node20
  main: src/index.js