name: Test

on:
    push:
    
jobs:
    test:
        runs-on: ubuntu-latest
        steps: 
           - uses: actions/checkout@v2
           - uses: actions/setup-node@v2
             with: 
                node-version: 20

           - name: Install dependencies
             run: npm ci
             
           - name: Create build
             run: npm run build
            
           - name: Remove node modules
             run: rm -rf node_modules

           - uses: ./
           - uses: ./
             with :
                person: 'Batman'