name: Test

on:
    push:
    
jobs:
    test:
        runs-on: ubuntu-latest
        steps: 
           - uses: actions/checkout@2
           - uses: actions/setup-node@v2
             with: 
                node-version: 20.14.0
           - uses: ./